name: flutter_music_player
description: A Flutter package to create a customizable music player application or module with ease
version: 0.0.1
homepage: https://github.com/AminBhst/flutter_music_player

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^1.0.1
  provider: ^6.0.3
  flutter_media_metadata: ^1.0.0
  palette_generator: ^0.3.3+1
  marquee: ^2.2.3
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  assets:
    - assets/image/play_button.png
    - assets/image/pause_button.png
    - assets/image/previous.png
    - assets/image/next.png
    - assets/image/drop.png
    - assets/image/album_cover_placeholder.png
